### ISSUE TITLE
No equation 10 in the mentioned paper

### ISSUE THREAD

**Issue by newbiecodie** [CarmenDAndrea/mmWave_Channel_Model#1]
Line 188 in Generate_Channel_frequency_selective_LTI.m mentions the consideration of LOS as in equation 10 of the paper "On Clustered Statistical MIMO Millimeter Wave Channel Simulation" but the last equation number in the paper is 9.

**Comment by CarmenDAndrea** [comment]
I noted now that this is a typo, it is Eq. (1). Thank you to spotting out it, I fixed it.
